apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kong
  name: kong
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
        app: external-gui
    spec:
      containers:
      - env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: postgres.dojot.svc.cluster.local
        - name: KONG_PG_USER
          value: postgres
        - name: KONG_PG_PASSWORD
          value: kong
        image: kong:0.10
        name: kong
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8001
      restartPolicy: Always

