apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: auth
  name: auth
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - image: agrotracking/auth:latest
        name: auth
        env:
        - name: KONG_URL
          value: http://kong:8001
        - name: MONGO_REPLICA_SET
          value: 'rs0'
      restartPolicy: Always
