apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gui
  name: gui
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gui
    spec:
      containers:
      - image: agrotracking/gui
        name: gui
      restartPolicy: Always
