apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mqtt
  name: mqtt
  namespace: dojot
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mqtt
        app: external-mqtt
    spec:
      containers:
      - image: ansi/mosquitto
        name: mqtt
        ports:
        - containerPort: 1883
      restartPolicy: Always
